// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdxvyirrtffhkmkghxjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkeHZ5aXJydGZmaGtta2doeGpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNzEzOTQsImV4cCI6MjA1NDg0NzM5NH0.RQk52XL0VU6tstJ7e3VyCmyMmysuwZmkfsx2w0grkjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);